#! /bin/sh
set -x
DIR=`dirname $0`
echo "dirname"
echo $DIR
if [ -x $DIR/inet -o -x $DIR/inet.exe ]; then
  $DIR/inet -n $DIR/../examples:$DIR $*
else
  opp_run -l $DIR/inet -n $DIR/../examples:$DIR $*
fi
